
---
title: "The K"
date: 2019-03-18
---

title: The K
author: Kailyn Marion
email: kailynmarion2016@gmail.co
description: > # this means to ignore newlines until "baseurl:"
  I will post art once a week.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
